name: Test and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        step: [ test, mypy, black, isort, pylint ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev --deploy --system

      - name: Run tests with pytest
        if: matrix.step == 'test'
        run: |
          pytest --cov=pkonfig --cov-report=xml tests/

      - name: Upload coverage reports to Codecov with GitHub Action
        if: matrix.step == 'test' && github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3

      - name: Check with mypy
        if: matrix.step == 'mypy'
        run: |
          mypy pkonfig/

      - name: Check imports order
        if: matrix.step == 'isort'
        run: |
          isort --check-only pkonfig

      - name: Format with black
        if: matrix.step == 'black'
        run: |
          black --check --diff pkonfig

      - name: Lint with pylint
        if: matrix.step == 'pylint'
        run: |
          pylint pkonfig
