name: Test and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev --deploy

      - name: Run tests with pytest
        run: |
          pytest tests/

      - name: Check with mypy
        run: |
          mypy pkonfig/

      - name: Check imports order
        run: |
          isort --check-only pkonfig

      - name: Format with black
        run: |
          black --check --diff pkonfig

      - name: Lint with pylint
        run: |
          pylint pkonfig
