name: Test and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        step: [test, mypy, black, isort, pylint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run tests with pytest
        if: matrix.step == 'test'
        run: |
          poetry run pytest --cov=pkonfig --cov-report=xml tests/

      - name: Upload coverage reports to Codecov with GitHub Action
        if: matrix.step == 'test' && github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3

      - name: Check with mypy
        if: matrix.step == 'mypy'
        run: |
          poetry run mypy pkonfig/

      - name: Check imports order
        if: matrix.step == 'isort'
        run: |
          poetry run isort --check-only pkonfig

      - name: Format with black
        if: matrix.step == 'black'
        run: |
          poetry run black --check --diff pkonfig

      - name: Lint with pylint
        if: matrix.step == 'pylint'
        run: |
          poetry run pylint pkonfig
