# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Python Package with Poetry

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for tags to be available

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Set package version from Git tag
        run: |
          TAG_NAME="${GITHUB_REF_NAME:-}"
          if [ -z "$TAG_NAME" ]; then
            # Fallback for manual runs or when ref name isn't populated
            TAG_NAME=$(git describe --tags --exact-match 2>/dev/null || git describe --tags --abbrev=0)
          fi
          # Strip a leading 'v' if present (allow tags like v1.2.3)
          POETRY_VERSION=${TAG_NAME#v}
          echo "Setting package version to $POETRY_VERSION from tag $TAG_NAME"
          poetry version "$POETRY_VERSION"

      - name: Build package
        run: poetry build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          activate-environment: conda-forge

      - name: Install conda dependencies
        run: |
          conda install -y -q anaconda-client conda-build conda-verify setuptools-scm pyyaml pytest

      - name: Build conda package
        run: |
          conda build --quiet --token=${{ secrets.ANACONDA }} .

